### ISSUE TITLE
Where's the real Wiki?

### ISSUE THREAD

**Issue by MoXiaoFreak** [GTDP/TecTech#1]
I'm interested in this addon for GTNH,but I don't know how to start with those doom-like multiblock machines.I found this Wiki site but I can't find anything else.So if you know how I can find tutorial of this mod,please tell me?

**Comment by SirAzazel** [comment]
Both wiki and mod is currently WIP, you cant really find much info on mod, but you can ask people on GTNH discord, including Tec himself. Other person that knows abit of info is 𝛿 Air Conditioner.
